//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.AnimalOwner = new HashSet<AnimalOwner>();
            this.Appointment = new HashSet<Appointment>();
            this.Reception = new HashSet<Reception>();
            this.VaccinationAnimal = new HashSet<VaccinationAnimal>();
        }
    
        public int IdAnimal { get; set; }
        public string AnimalName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> IdBreed { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdCategoryAnimal { get; set; }
        public Nullable<int> IdGender { get; set; }
        public Nullable<int> IdTypeAnimal { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public string Description { get; set; }
    
        public virtual Breed Breed { get; set; }
        public virtual CategoryAnimal CategoryAnimal { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeAnimal TypeAnimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalOwner> AnimalOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Reception { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinationAnimal> VaccinationAnimal { get; set; }
    }
}
