//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalHistory
    {
        public int IdAnimalHistory { get; set; }
        public Nullable<int> IdAnimalOwner { get; set; }
        public Nullable<int> IdServiceReception { get; set; }
        public Nullable<int> IdMedicineAppointment { get; set; }
        public Nullable<int> IdAppointment { get; set; }
    
        public virtual AnimalOwner AnimalOwner { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual MedicineAppointment MedicineAppointment { get; set; }
        public virtual ServiceReception ServiceReception { get; set; }
    }
}
