//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineAppointment()
        {
            this.AnimalHistory = new HashSet<AnimalHistory>();
        }
    
        public int IdMedicineAppointment { get; set; }
        public Nullable<int> IdAppointment { get; set; }
        public Nullable<int> IdMedicine { get; set; }
        public double Dose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalHistory> AnimalHistory { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
