//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationAnimal
    {
        public int IdVaccinationAnimal { get; set; }
        public Nullable<int> IdMedicine { get; set; }
        public Nullable<int> IdAnimal { get; set; }
        public Nullable<System.DateTime> DateVaccination { get; set; }
        public Nullable<System.DateTime> DateRepeat { get; set; }
        public Nullable<bool> Finish { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
